#!/usr/bin/env python3
import sys, json, os
import soundfile as sf
import numpy as np
from kokoro_onnx import Kokoro

def main():
    # Paths for model and voices
    # Check multiple locations: root, src, or models/
    possible_paths = [
        ".",
        "models",
        "src",
        "../models",
        ".."
    ]
    
    model_file = "kokoro-v1.0.onnx"
    voices_file = "voices-v1.0.bin"
    
    model_path = None
    voices_path = None
    
    for p in possible_paths:
        m = os.path.join(p, model_file)
        v = os.path.join(p, voices_file)
        if os.path.exists(m):
            model_path = m
        if os.path.exists(v):
            voices_path = v
            
    try:
        if not model_path or not os.path.exists(model_path):
            raise FileNotFoundError(f"Model file {model_file} not found in {possible_paths}")
        if not voices_path or not os.path.exists(voices_path):
            raise FileNotFoundError(f"Voices file {voices_file} not found in {possible_paths}")
            
        kokoro = Kokoro(model_path, voices_path)
        print("ready", flush=True)
    except Exception as e:
        print(json.dumps({"status": "error", "error": f"Model initialization failed: {e}"}), flush=True)
        return

    # Use binary stdin for robust UTF-8 on Windows
    stdin = sys.stdin.buffer
    for line_bytes in stdin:
        try:
            line = line_bytes.decode('utf-8').strip()
            if not line:
                continue
            req = json.loads(line)
            action = req.get('action')
            
            if action == 'synthesize':
                text = req.get('text', '')
                voice = req.get('voice', 'af_bella')
                speed = req.get('speed', 1.0)
                output_path = req.get('output_path', 'temp.wav')
                
                if not text:
                    print(json.dumps({"status": "error", "error": "Empty text provided"}), flush=True)
                    continue

                # Generate audio using kokoro-onnx
                # kokoro-onnx returns (samples, sample_rate)
                samples, sample_rate = kokoro.create(text, voice=voice, speed=speed)
                
                if samples is None or len(samples) == 0:
                    print(json.dumps({"status": "error", "error": "No audio generated by model"}), flush=True)
                    continue
                
                # Write to disk
                sf.write(output_path, samples, sample_rate)
                
                duration = len(samples) / float(sample_rate)
                print(json.dumps({"status": "success", "duration": duration}), flush=True)
                
        except Exception as e:
            print(json.dumps({"status": "error", "error": str(e)}), flush=True)

if __name__ == '__main__':
    main()
